# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50b76d3b7a092a6b669542c0826f2453b1df2574caacdc65502a185519a1d484f748aef5a7101374bc8fda82141e20a1295679217cbb46ed34942c33837f2e24

test:
  secret_key_base: c4d29058d2279226d445c5b06f80fe0bff8a176452db61d462b44f3e0189bc2daa457847ce704e8e33af8d65267a1f83a7d38961f4c91c11fc2f6760f3f8d8a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
