# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd2b1f244526451cd2936ab27548a812d410bcaf5e471d8f9aa9e31d0e46963db24ec8e5b14966a22c864820644ad12f4b5a48dcc18853185cb39592f9c9be72

test:
  secret_key_base: 6d530040931bec184cb0098b963f41d0ff45928014437e4a9122a9cf339816bf44b62bfb6a540b00020c7aea56d0d0210f137a3de917a3186a553de409ea439d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
