# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8447362cded995fe165aecb42c25d435a6950c548776491c53633b41431ca8318ce936573bc4c77e0bfd3dcc412b4995e97d2873d8042fa422bfd0853bd4f9f8

test:
  secret_key_base: 42d26848088c2076800f96518b899a27b2e75b6a440a1a8541befab9f43fab4498281214106636e3fc8a97ce2c74c9618cc5d1e056526ba8a3d4aa4a87fed22d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
